# The following redirect is intended for use with most SPAs
# that handle routing internally.


[[redirects]]
  from = "/api"
  to = "https://gooder-bank-server.herokuapp.com/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200