# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api"
  to = "https://api.mysearch.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect